// STORE THE CONSTANTS TO BE USED IN ACTIONS & REDUCERS
export const LOAD_STORE = 'LOAD_STORE';
export const SHOW_CHARACTER_DETAIL= 'SHOW_CHARACTER_DETAIL';
export const UPDATE_VOTE = 'UPDATE_VOTE';
export const SAVE_COMMENT = 'SAVE_COMMENT';
